- name: Log into registry
  shell: "docker login 34.219.139.12:5000 -u user -p 123"

- name: Pull image from registry
  shell: "docker pull  34.219.139.12:5000/backimage"

- name: Run container for back image
  docker_container:
    name: movie-analyst-ui
    image: 34.219.139.12:5000/backimage
    state: started
    volumes:
      - "/etc/docker/movie-analyst-api:/var/lib/movie-analyst-api"
    ports:
      - "3000:3000"
    env:
      BACKEND_URL: "10.0.4.244:3000"
      DB_HOST: "host"
      DB_USER: "user"
      DB_PASS: "pass"

- name: Run seed
  shell: | 
    docker exec -it movie-analyst-api shell
    node seeds.js
